import {defineField, defineType} from 'sanity'

const jsonField = (name: string, title: string) => defineField({
  name,
  title,
  type: 'text',
  rows: 12,
  description: 'Structured JSON generated by Magnafic Copilot.',
})

export const researchSessionSchema = defineType({
  name: 'researchSession',
  title: 'Research Session',
  type: 'document',
  fields: [
    defineField({
      name: 'project',
      title: 'Project',
      type: 'reference',
      to: [{type: 'researchProject'}],
      validation: (Rule) => Rule.required(),
    }),
    jsonField('scoutOutput', 'Topic Scout Output'),
    jsonField('researchOutput', 'Research Output'),
    jsonField('synthesizedOutput', 'Synthesized Output'),
    jsonField('finalOutput', 'Final Output'),
    defineField({name: 'createdAt', title: 'Created At', type: 'datetime', readOnly: true}),
  ],
  orderings: [{title: 'Newest First', name: 'createdAtDesc', by: [{field: 'createdAt', direction: 'desc'}]}],
})
